### ISSUE TITLE
convert the yolov3-tiny model to caffe model

### ISSUE THREAD

**Issue by SSTTfit** [ChenYingpeng/caffe-yolov3#58]
Thanks for your help!
When I convert the yolov3-tiny model to caffe model, I got this error.
I saved prototxt successfully but can't convert the weightfile.  

Traceback (most recent call last):
  File "/home/mitc/ljy/darknet2caffe/darknet2caffe.py", line 540, in <module>
    darknet2caffe(cfgfile, weightfile, protofile, caffemodel)
  File "/home/mitc/ljy/darknet2caffe/darknet2caffe.py", line 18, in darknet2caffe
    params = net.params
  File "/home/mitc/ljy/caffe/python/caffe/pycaffe.py", line 67, in _Net_params
    self._layer_names, self.layers)
  File "/home/mitc/ljy/caffe/python/caffe/pycaffe.py", line 68, in <listcomp>
    if len(lr.blobs) > 0])
OverflowError: cannot fit 'int' into an index-sized integer
*** Error in `/home/mitc/ljy/anaconda3/bin/python3.6': free(): invalid pointer: 0x000000000b7ae728 ***

**Comment by ChenYingpeng** [comment]
Please look this link #25.
